engine_config:
  enforce_eager: true
  limit_mm_per_prompt:
    image: 1
  max_model_len: 128000
  max_num_seqs: 16
  model: meta-llama/Llama-3.2-11B-Vision-Instruct
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: meta-llama/Llama-3.2-11B-Vision-Instruct
  openllm_alias: 11b-vision-lm
project: vllm-chat
service_config:
  name: llama3.2
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
