alias:
- 12b-no-cache
engine_config:
  enable_prefix_caching: false
  max_model_len: 16384
  model: google/gemma-3-12b-it
project: vllm-chat
service_config:
  envs:
  - name: HF_TOKEN
  name: gemma3
  resources:
    gpu: 1
    gpu_type: nvidia-tesla-a100
  traffic:
    timeout: 300
