chat_template: mistral-instruct
engine_config:
  quantization: awq
  enforce_eager: true
  max_model_len: 32768
  model: solidrust/Codestral-22B-v0.1-hf-AWQ
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: solidrust/Codestral-22B-v0.1-hf-AWQ
  openllm_alias: 22b-awq-lm,22b-v0.1-awq-lm
project: vllm-chat
service_config:
  name: codestral
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80g
  traffic:
    timeout: 300
